Skipping apply if nothing changed

diff --git a/.github/workflows/production.yaml b/.github/workflows/production.yaml
--- a/.github/workflows/production.yaml
+++ b/.github/workflows/production.yaml
@@ -22,7 +22,8 @@ jobs:
           aws-region: ${{ secrets.AWS_REGION }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
       - run: pip install -r platform/requirements.txt
-      - uses: pulumi/actions@v6
+      - name: preview
+        uses: pulumi/actions@v6
         with:
           command: preview
           stack-name: organization/production
@@ -30,13 +31,24 @@ jobs:
           work-dir: platform
           comment-on-pr: true
           comment-on-summary: true
+          color: always
         env:
           PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
+      - name: Set job output based on preview exit code
+        # If preview_exit_code was 1 (error), we want the job to fail.
+        # Otherwise, we output the actual exit code from preview.
+        run: |
+          if [ "${{ steps.preview.outputs.exit_code }}" == "1" ]; then
+            echo "Pulumi preview failed with an error."
+            exit 1
+          fi
+          echo "preview_exit_code=${{ steps.preview.outputs.exit_code }}" >> "$GITHUB_OUTPUT"
 
   update_production:
     environment: production
     name: Update Production
     runs-on: ubuntu-latest
+    if: needs.pulumi_preview.outputs.preview_exit_code == '2'
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v5
diff --git a/.github/workflows/staging.yaml b/.github/workflows/staging.yaml
--- a/.github/workflows/staging.yaml
+++ b/.github/workflows/staging.yaml
@@ -1,6 +1,7 @@
 ---
 name: Pulumi Staging
 on:
+  workflow_dispatch: {}
   push:
     branches:
       - main
@@ -31,11 +32,21 @@ jobs:
           comment-on-summary: true
         env:
           PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
+      - name: Set job output based on preview exit code
+        # If preview_exit_code was 1 (error), we want the job to fail.
+        # Otherwise, we output the actual exit code from preview.
+        run: |
+          if [ "${{ steps.preview.outputs.exit_code }}" == "1" ]; then
+            echo "Pulumi preview failed with an error."
+            exit 1
+          fi
+          echo "preview_exit_code=${{ steps.preview.outputs.exit_code }}" >> "$GITHUB_OUTPUT"
 
   update_staging:
     environment: staging
     name: Update Staging
     runs-on: ubuntu-latest
+    if: needs.pulumi_preview.outputs.preview_exit_code == '2'
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v5
